---
config:
  email_subject: SECRET SANTA
  smtp:
    host: smtp.gmail.com
    port: 465
    user: muad.dib@example.com
    # If pass starts with a $, it is assumed to be the name of an env var
    # if your password actually starts with a dollar sign, escape it as \$
    password: $GMAIL_PASS
  # Details to use for sending test e-mails
  testing:
    name: Paul Atreides
    email: muad.dib@example.com
rules:
  # The dollar limit for your secret santa
  limit_dollars: 30.00
  # The date when the exchange of gifts will take place
  opening_day: 2022-12-25
participants:
  - name: Leto II
    email: theduke@example.com
  - name: Duncan Idaho
    email: duncan_idahohoho@example.com
  - name: Paul Atreides
    email: muad.dib@example.com
  - name: Feyd & Rabban
    email: bifar@example.com